sudo: false
language: python
python: '2.7'
services:
  - docker

cache:
    directories:
      - $HOME/.cache

git:
    depth: 100500

stages:
  - test
  - name: deploy
    # Deploy packages to PackageCloud from tags and master
    # see:
    #   * https://github.com/tarantool/tarantool/issues/3745
    #   * https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
    # Also skip deploys for pull-requests, api and cron events.
    if: (type = push) AND (branch = master OR tag IS present) AND (env(PACKAGECLOUD_TOKEN) IS present)

env:
    global:
      - PRODUCT=tarantool-vshard
      - ROCK_NAME=vshard

before_script:
  - git describe --long

_deploy_to_packagecloud: &deploy_to_packagecloud
  provider: packagecloud
  username: tarantool
  token: $PACKAGECLOUD_TOKEN
  dist: $OS/$DIST
  package_glob: build/*.{rpm,deb}
  skip_cleanup: true
  on:
    all_branches: true # it's restricted with the condition for deploy stage

# Pack and deploy packages to PackageCloud
_packpack: &packpack
  stage: deploy
  script:
    - git clone https://github.com/packpack/packpack.git
    - packpack/packpack -e PACKPACK_GIT_SOURCEDIR=/source/
    - ls -l build/
  deploy:
    - <<: *deploy_to_packagecloud
      repository: "1_10"
    - <<: *deploy_to_packagecloud
      repository: "2x"
    - <<: *deploy_to_packagecloud
      repository: "2_2"
    - <<: *deploy_to_packagecloud
      repository: "2_3"
    - <<: *deploy_to_packagecloud
      repository: "2_4"

_test-run: &test-run
  before_script:
    - git submodule update --init --recursive
    - pip install -r test/requirements.txt
    # This command accepts VER envar to select tarantool version.
    - curl -L https://tarantool.io/installer.sh | sudo -E bash
    - sudo apt-get install -y tarantool tarantool-dev
    - cmake .
  script: make test

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always

jobs:
  include:
    - <<: *test-run
      env: VER=1.10
    - <<: *test-run
      env: VER=2.2
      allow_failure: true
    - <<: *test-run
      env: VER=2.4
    - stage: deploy
      script: skip
      deploy:
        - provider: script
          script: curl --fail -X PUT -F rockspec=@$ROCK_NAME-scm-1.rockspec
            https://$ROCKS_USERNAME:$ROCKS_PASSWORD@$ROCKS_SERVER
        - on:
            tags: true
          provider: script
          script: cat $ROCK_NAME-scm-1.rockspec |
            sed -E
              -e "s/branch = '.+'/tag = '$TRAVIS_TAG'/g"
              -e "s/version = '.+'/version = '$TRAVIS_TAG-1'/g" |
            curl --fail -X PUT -F "rockspec=@-;filename=$ROCK_NAME-$TRAVIS_TAG-1.rockspec"
              https://$ROCKS_USERNAME:$ROCKS_PASSWORD@$ROCKS_SERVER
    - <<: *packpack
      env: OS=el DIST=6
    - <<: *packpack
      env: OS=el DIST=7
    - <<: *packpack
      env: OS=el DIST=8
    - <<: *packpack
      env: OS=fedora DIST=28
    - <<: *packpack
      env: OS=fedora DIST=29
    - <<: *packpack
      env: OS=fedora DIST=30
    - <<: *packpack
      env: OS=fedora DIST=31
    - <<: *packpack
      env: OS=ubuntu DIST=trusty
    - <<: *packpack
      env: OS=ubuntu DIST=xenial
    - <<: *packpack
      env: OS=ubuntu DIST=bionic
    - <<: *packpack
      env: OS=ubuntu DIST=disco
    - <<: *packpack
      env: OS=ubuntu DIST=eoan
    - <<: *packpack
      env: OS=debian DIST=jessie
    - <<: *packpack
      env: OS=debian DIST=stretch
    - <<: *packpack
      env: OS=debian DIST=buster
